name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:

  matrix_build:
    strategy:
      matrix:
        otp-version: ['22', '23', '24']
        # erlef/setup-beam action does not support macos yet
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      # Set to 1 for verbose rebar3 logging
      DEBUG: 0
      # Set to 1 for even more verbose rebar3 logging
      DIAGNOSTIC: 0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup Erlang
        uses: ./.github/actions/setup-beam
        with:
          otp-version: ${{ matrix.otp-version }}
          rebar3-version: '3.17'
      - name: Setup MSVC toolchain
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ./.github/actions/msvc-dev-cmd
      - name: Compile
        run: rebar3 compile
      - name: EUnit tests
        run: rebar3 eunit
      - name: Setup tmate session on job failure
        uses: ./.github/actions/tmate
        if: ${{ failure() }}
        with:
          limit-access-to-actor: true

